### PR TITLE
fixed 1 high severity vulnerability: "axios": "0.20.0" -> "0.21.1"

### PR DESCRIPTION
**Pull request by sjkummer**
Updated to latest @nestjs/common too.

### CODE REVIEW

**Comment by sjkummer** [comment]
@jukkahell FYI

**Comment by jukkahell** [comment]
Thanks mate! I personally dont like the ^ in version number to prevent any sudden incidents but I trust that nestjs knows how versioning works. So this is good 😊👌

**Comment by sjkummer** [comment]
@jukkahell Thanks for merging :-)

Are there any plans for a new npm release?

I have tried to use the github version of this lib in `package.json` to silent npm audit:
` "nest-logger": "github:jukkahell/nestlogger#a23fec0846b7e9553774f09edb3515efae4a4935"`

But the `github:` way seems to be broken for this package. Most files are missing after that in node_modules/nestlogger (especially the sourcecode). I haven't yet figured out why. This typically happens if an `.npmignore` file is involved, but I didn't see one 🤔

```
$ node_modules/nest-logger
$ ls -la
total 24
drwxr-xr-x    5 sku  staff    160 Mar  5 10:34 .
drwxr-xr-x  908 sku  staff  29056 Mar  5 10:35 ..
-rw-r--r--    1 sku  staff   6196 Oct 26  1985 README.md
drwxr-xr-x   10 sku  staff    320 Mar  5 10:34 node_modules
-rw-r--r--    1 sku  staff   3523 Mar  5 10:34 package.json
```

**Comment by jukkahell** [comment]
Absolutely! Sorry for taking so long with this. I released 6.2.0 just now. I also increased the NestJS core version to match with the common lib.

**Comment by sjkummer** [comment]
Great, thanks  🙌

**Pull request merged**
